# Generated by Django 5.1.4 on 2025-01-08 02:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Unitallocation', '0010_rename_school_facultyfield_school_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('scale', 'Scale'), ('comment', 'Comment')], max_length=10)),
                ('scale_min', models.IntegerField(blank=True, null=True)),
                ('scale_max', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Semester', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Unitallocation.semester')),
                ('academicYear', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Unitallocation.academicyear')),
                ('course', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Unitallocation.course')),
                ('faculty', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Unitallocation.faculty')),
                ('unit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Unitallocation.unit')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(blank=True, null=True)),
                ('response_scale', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluation')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationquestion')),
            ],
            options={
                'unique_together': {('evaluation', 'question')},
            },
        ),
    ]
