# Generated by Django 5.1.4 on 2024-12-17 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unitallocation', '0006_course_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='School',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Unitallocation.school'),
        ),
    ]
