# Generated by Django 5.1.4 on 2024-12-17 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unitallocation', '0007_unit_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='School',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Unitallocation.school'),
        ),
    ]
