# Generated by Django 5.1.4 on 2024-12-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Unitallocation', '0008_alter_unit_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='School',
            new_name='school',
        ),
    ]
