# Generated by Django 5.1.4 on 2025-01-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unitallocation', '0011_rename_facultyfield_field_unit_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='field',
        ),
        migrations.AddField(
            model_name='faculty',
            name='field',
            field=models.ManyToManyField(to='Unitallocation.field'),
        ),
    ]
