# Generated by Django 5.1.4 on 2025-01-14 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Unitallocation', '0013_remove_faculty_field_faculty_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='field',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='field',
        ),
        migrations.AddField(
            model_name='faculty',
            name='field',
            field=models.ManyToManyField(to='Unitallocation.field'),
        ),
        migrations.AddField(
            model_name='unit',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Unitallocation.field'),
        ),
    ]
